import { SupportedChains } from "../constants/networks";

export type ContractAddresses = {
  WNAT: string;
  WBTC: string;
  WETH: string;
  USDC: string;
  OPTIONS_AUTHORITY: string;
  VAULT_PRICE_FEED: string;
  OPTIONS_MARKET: string;
  S_VAULT: string;
  M_VAULT: string;
  L_VAULT: string;
  S_VAULT_UTILS: string;
  M_VAULT_UTILS: string;
  L_VAULT_UTILS: string;
  S_USDG: string;
  M_USDG: string;
  L_USDG: string;
  S_OLP: string;
  M_OLP: string;
  L_OLP: string;
  S_OLP_MANAGER: string;
  M_OLP_MANAGER: string;
  L_OLP_MANAGER: string;
  S_REWARD_TRACKER: string;
  M_REWARD_TRACKER: string;
  L_REWARD_TRACKER: string;
  S_REWARD_DISTRIBUTOR: string;
  M_REWARD_DISTRIBUTOR: string;
  L_REWARD_DISTRIBUTOR: string;
  S_REWARD_ROUTER_V2: string;
  M_REWARD_ROUTER_V2: string;
  L_REWARD_ROUTER_V2: string;
  CONTROLLER: string;
  POSITION_MANAGER: string;
  SETTLE_MANAGER: string;
  FEE_DISTRIBUTOR: string;
  BTC_OPTIONS_TOKEN: string;
  ETH_OPTIONS_TOKEN: string;
  FAST_PRICE_EVENTS: string;
  FAST_PRICE_FEED: string;
  POSITION_VALUE_FEED: string;
  SETTLE_PRICE_FEED: string;
  SPOT_PRICE_FEED: string;
  PRIMARY_ORACLE: string;
  VIEW_AGGREGATOR: string;
  REFERRAL: string;

  // Optional Berachain specific addresses
  WBERA?: string;
  HONEY?: string;
  BHONEY?: string;
  BERA?: string;
  BYUSD?: string;
  "HONEY-WBTC LP"?: string;
  "USDC.e-HONEY LP"?: string;
  "BYUSD-HONEY LP"?: string;
  "WBERA-HONEY LP"?: string;
  DOV_SWAP_UTIL?: string;
  DOV_VAULT_QUEUE_EVENTS?: string;
  DOV_WBERA_HONEY?: string;
  DOV_VAULT_QUEUE_WBERA_HONEY?: string;
  DOV_BYUSD_HONEY?: string;
  DOV_VAULT_QUEUE_BYUSD_HONEY?: string;
  DOV_USDC_HONEY?: string;
  DOV_VAULT_QUEUE_USDC_HONEY?: string;
};

export type ContractAddressMap = {
  [key in SupportedChains]: ContractAddresses;
};
