/**
 * This code was generated by Builder.io
 */
import React from "react";
import StrategyDetails from "./StrategyDetails";
import StrategyMetrics from "./StrategyMetrics";
import { strategies } from "@/constants/constants.dov";
import Button from "@/components/Common/Button";
import { twJoin } from "tailwind-merge";
import DesktopOnly from "@/components/Common/DesktopOnly";

type Props = {
  strategy: string,
  underlying: string,
  apy: number,
}

const OptionsStrategy: React.FC<Props> = ({
  strategy,
  underlying,
  apy,
}) => {
  return (
    <section
      className={twJoin(
        "flex flex-col items-start w-full",
        "dt:px-[28px] dt:mt-[36px] dt:h-full",
      )}
    >
      <DesktopOnly className="w-full">
        <div
          className={twJoin(
            "w-full",
            "flex justify-between",
          )}
        >
          <span className="text-[20px] font-semibold text-greenE6">
            Options Strategy
          </span>
          <Button
            name="Learn More"
            color=""
            className={twJoin(
              "w-[128px]",
              "mt-auto",
              "h-[32px]",
              "text-greenc1 border border-greenc1",
            )}
            onClick={() => {
              window.open("https://docs.moby.trade/how-its-built/defi-options-vault/berachain-defi-options-vault/options-strategy", "_blank")
            }}
          />
        </div>
      </DesktopOnly>
      <h3 className={twJoin(
        "dt:mt-[28px] dt:mb-0 dt:text-[16px]",
        "mb-[16px] text-[14px]",
        "font-semibold leading-none text-whitee0",
      )}>
        {strategies[strategy].title}
      </h3>
      <StrategyDetails strategy={strategy} />
      <StrategyMetrics strategy={strategy} underlying={underlying} apy={apy} />
    </section>
  );
};

export default OptionsStrategy;
