/**
 * This code was generated by Builder.io
 */
import { strategies } from "@/constants/constants.dov";
import React from "react";
import { twJoin } from "tailwind-merge";

type Props = {
  strategy: string,
}

const StrategyDetails: React.FC<Props> = ({ strategy }) => {
  return (
    <div className="flex flex-col w-full mb-[24px]">
      <div
        className={twJoin(
          "grid gap-[16px]",
          "dt:grid-cols-[470px,1fr]",
          "w-full"
        )}
      >
        <div
          className={twJoin(
            "flex flex-col",
          )}
        >
          {strategies[strategy].description}
        </div>

        <img
          className={twJoin(
            "dt:w-auto",
            "w-[234px] mx-auto",
          )}
          src={strategies[strategy].imgSrc}
        />
      </div>
    </div>
  );
};

export default StrategyDetails;
