/**
 * This code was generated by Builder.io
 */
import React from "react";
import { twJoin } from "tailwind-merge";

interface BalanceInfoProps {
  label: string | React.ReactNode;
  amount: string | number;
  value?: string;
  tokenIcon?: string;
}

const BalanceInfo: React.FC<BalanceInfoProps> = ({
  label,
  amount,
  value,
  tokenIcon,
}) => {
  
  return (
    <div className="flex flex-col items-start">
      <div className={twJoin(
        "mb-[8px]",
        "dt:mb-[12px]",
      )}>
        <span
          className={twJoin([
            "text-[12px] leading-[18px] text-gray80",
            "mb-[1px]",
            "dt:text-[14px]",
          ])}
        >
          {label}
        </span>
      </div>
      <div 
        className={twJoin(
          "flex items-center",
          "dt:mb-[8px]",
        )}
      >
        {tokenIcon && (
          <img src={tokenIcon} alt="" className="w-[18px] h-[18px] mr-[4px]" />
        )}
        <span
          className={twJoin([
            "text-[16px] leading-[18px] text-whitee0 font-[600]",
            "dt:font-graphie",
            "font-plex-mono",
          ])}
        >
          {amount}
        </span>
      </div>
      {value && (
        <span 
          className={twJoin(
            "text-[13px] leading-[18px] text-gray80 font-[600]",
            "dt:font-graphie dt:text-[14px]",
            "font-plex-mono",
          )}
        >
          {value}
        </span>
      )}
    </div>
  );
};

export default BalanceInfo;
