/**
 * This code was generated by Builder.io
 */
import React from "react";
import { twJoin } from "tailwind-merge";

interface RewardItemProps {
  iconSrc: string;
  title: string;
  apy?: string;
  description: string;
}

const RewardItem: React.FC<RewardItemProps> = ({
  iconSrc,
  title,
  apy,
  description,
}) => {
  return (
    <div className="flex flex-col mb-[16px]">
      <div
        className={twJoin(
          "flex gap-[16px] items-start text-[15px]",
          "dt:text-[16px]"
        )}
      >
        <img
          loading="lazy"
          src={iconSrc}
          alt=""
          className="object-contain shrink-0 w-[24px] h-[24px] relative top-[1px]"
        />
        <div className="flex flex-col flex-auto gap-[6px]">
          <div
            className={twJoin(
              "flex items-center",
            )}
          >
            <div
              className={twJoin(
                "text-whitee0 text-[15px] font-[600] mr-[6px]",
                "dt:text-[16px]"
              )}
            >{title}</div>
            {apy && <div className="text-green63 font-[600]">{apy}</div>}
          </div>
          <div
            className={twJoin(
              "text-[13px] font-[500] text-gray99 leading-[18px]",
              "dt:text-[14px] dt:font-[600]"
            )}
          >
            {description}
          </div>
        </div>
      </div>
    </div>
  );
};

export default RewardItem;
