/**
 * This code was generated by Builder.io
 */
import React from "react";
import RewardItem from "./RewardItem";
import { aprMetadata } from "@/constants/constants.dov";
import { advancedFormatNumber } from "@/utils/helper";
import DesktopOnly from "@/components/Common/DesktopOnly";
import { twJoin } from "tailwind-merge";

type Props = {
  apyIngredients: any;
}

const RewardsComponent: React.FC<Props> = ({
  apyIngredients,
}) => {

  return (
    <section 
      className={twJoin(
        "flex flex-col w-full rounded-[12px] ",
        "dt:px-[28px] dt:pt-[36px] dt:pb-[40px] dt:mt-[24px] dt:bg-black1a",
      )}
    >
      <DesktopOnly>
        <h2 className="self-start text-[20px] font-[600] text-greenE6 mb-[28px]">Rewards</h2>
      </DesktopOnly>

      {apyIngredients?.map(({ key, title, apy }: any) => {
        return (
          <RewardItem 
            key={title}
            title={title} 
            apy={typeof apy == "number" ? `+${advancedFormatNumber(apy, 1, "", true)}% APY` : ""}
            iconSrc={aprMetadata[key].iconSrc}
            description={aprMetadata[key].description}
          />
        )
      })}
    </section>
  );
};

export default RewardsComponent;
