import { ChainId } from "./constants.networks"

const REQUIREMENTS = {
  [ChainId.ARBITRUM_ONE]: {
    GOOGLE_SPREADSHEET_ID: '1I-52M_Rg7xV1VdkcFdaoj8eR3bft4AGeWW2DGZJhlXg',
    
    DUNE_DATA_BUCKET: 'moby-arb-data',
    MOBY_DATA_OLP_DASHBOARD_KEY: 'olp-pool-dashboard-data.json',
    DUNE_QUERY_ID_FEES_AND_RP: 4451092,
    DUNE_QUERY_ID_NOTIONAL_VOLUME: 3666797,
    DUNE_QUERY_ID_PNL: 3970242,
    DUNE_QUERY_ID_DISTRIBUTED_ETH_REWARD: 4598370,
    DUNE_QUERY_ID_OLP_INFO: 4598484,

    SLACK_NOTIFICATION_CHANNEL_ID: 'C07BKCCD38A',
    SLACK_ALERT_CHANNEL_ID: 'C07BKCB0NFL',
    SLACK_TRADE_CHANNEL_ID: 'C08BMA26WMR',
    TX_SERVICE_URL: "",
    MAX_POSITION_PROCESS_ITEMS: 12,
    MAX_SETTLE_POSITION_PROCESS_ITEMS: 8,
    DEADLINE_SECONDS: 30,
  },
  [ChainId.BERACHAIN_MAINNET]: {
    GOOGLE_SPREADSHEET_ID: '1U1fDBxXMHncjbcrFyvevNXVpZVaKGPyPWZcHXV1pqi8',

    DUNE_DATA_BUCKET: 'moby-arb-data',
    MOBY_DATA_OLP_DASHBOARD_KEY: 'olp-pool-dashboard-data-berachain.json',
    DUNE_QUERY_ID_FEES_AND_RP: 4679814,
    DUNE_QUERY_ID_NOTIONAL_VOLUME: 4679863,
    DUNE_QUERY_ID_PNL: 4679942,
    DUNE_QUERY_ID_DISTRIBUTED_ETH_REWARD: 4679823,
    DUNE_QUERY_ID_OLP_INFO: 4679831,

    SLACK_NOTIFICATION_CHANNEL_ID: 'C07C8646L8G',
    SLACK_ALERT_CHANNEL_ID: 'C07BMSF9WG4',
    SLACK_TRADE_CHANNEL_ID: 'C08C075P142',
    TX_SERVICE_URL: "https://transaction.safe.berachain.com/api",
    MAX_POSITION_PROCESS_ITEMS: 4,
    MAX_SETTLE_POSITION_PROCESS_ITEMS: 4,
    DEADLINE_SECONDS: 30,
  }
}

export default REQUIREMENTS